// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: values.go.tmpl

package values

import (
	"fmt"
)

type Type int

const (
	Int Type = iota
	Int8
	Int16
	Int32
	Int64
	Uint
	Uint8
	Uint16
	Uint32
	Uint64
	String
	Bool
)

type Value interface {
	Type() Type
	Get() interface{}
	IsNull() bool
	Int() int
	Int8() int8
	Int16() int16
	Int32() int32
	Int64() int64
	Uint() uint
	Uint8() uint8
	Uint16() uint16
	Uint32() uint32
	Uint64() uint64
	String() string
	Bool() bool
}

type intValue struct {
	v int
}

func (v intValue) Type() Type {
	return Int
}

func (v intValue) Get() interface{} {
	return v.v
}

func (v intValue) IsNull() bool {
	return false
}

func (v intValue) Int() int {
	return v.v
}

func (v intValue) Int8() int8 {
	panic("cannot get int8 out of int")
}

func (v intValue) Int16() int16 {
	panic("cannot get int16 out of int")
}

func (v intValue) Int32() int32 {
	panic("cannot get int32 out of int")
}

func (v intValue) Int64() int64 {
	panic("cannot get int64 out of int")
}

func (v intValue) Uint() uint {
	panic("cannot get uint out of int")
}

func (v intValue) Uint8() uint8 {
	panic("cannot get uint8 out of int")
}

func (v intValue) Uint16() uint16 {
	panic("cannot get uint16 out of int")
}

func (v intValue) Uint32() uint32 {
	panic("cannot get uint32 out of int")
}

func (v intValue) Uint64() uint64 {
	panic("cannot get uint64 out of int")
}

func (v intValue) Bool() bool {
	panic("cannot get bool out of int")
}

func (v intValue) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type int8Value struct {
	v int8
}

func (v int8Value) Type() Type {
	return Int8
}

func (v int8Value) Get() interface{} {
	return v.v
}

func (v int8Value) IsNull() bool {
	return false
}

func (v int8Value) Int() int {
	panic("cannot get int out of int8")
}

func (v int8Value) Int8() int8 {
	return v.v
}

func (v int8Value) Int16() int16 {
	panic("cannot get int16 out of int8")
}

func (v int8Value) Int32() int32 {
	panic("cannot get int32 out of int8")
}

func (v int8Value) Int64() int64 {
	panic("cannot get int64 out of int8")
}

func (v int8Value) Uint() uint {
	panic("cannot get uint out of int8")
}

func (v int8Value) Uint8() uint8 {
	panic("cannot get uint8 out of int8")
}

func (v int8Value) Uint16() uint16 {
	panic("cannot get uint16 out of int8")
}

func (v int8Value) Uint32() uint32 {
	panic("cannot get uint32 out of int8")
}

func (v int8Value) Uint64() uint64 {
	panic("cannot get uint64 out of int8")
}

func (v int8Value) Bool() bool {
	panic("cannot get bool out of int8")
}

func (v int8Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type int16Value struct {
	v int16
}

func (v int16Value) Type() Type {
	return Int16
}

func (v int16Value) Get() interface{} {
	return v.v
}

func (v int16Value) IsNull() bool {
	return false
}

func (v int16Value) Int() int {
	panic("cannot get int out of int16")
}

func (v int16Value) Int8() int8 {
	panic("cannot get int8 out of int16")
}

func (v int16Value) Int16() int16 {
	return v.v
}

func (v int16Value) Int32() int32 {
	panic("cannot get int32 out of int16")
}

func (v int16Value) Int64() int64 {
	panic("cannot get int64 out of int16")
}

func (v int16Value) Uint() uint {
	panic("cannot get uint out of int16")
}

func (v int16Value) Uint8() uint8 {
	panic("cannot get uint8 out of int16")
}

func (v int16Value) Uint16() uint16 {
	panic("cannot get uint16 out of int16")
}

func (v int16Value) Uint32() uint32 {
	panic("cannot get uint32 out of int16")
}

func (v int16Value) Uint64() uint64 {
	panic("cannot get uint64 out of int16")
}

func (v int16Value) Bool() bool {
	panic("cannot get bool out of int16")
}

func (v int16Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type int32Value struct {
	v int32
}

func (v int32Value) Type() Type {
	return Int32
}

func (v int32Value) Get() interface{} {
	return v.v
}

func (v int32Value) IsNull() bool {
	return false
}

func (v int32Value) Int() int {
	panic("cannot get int out of int32")
}

func (v int32Value) Int8() int8 {
	panic("cannot get int8 out of int32")
}

func (v int32Value) Int16() int16 {
	panic("cannot get int16 out of int32")
}

func (v int32Value) Int32() int32 {
	return v.v
}

func (v int32Value) Int64() int64 {
	panic("cannot get int64 out of int32")
}

func (v int32Value) Uint() uint {
	panic("cannot get uint out of int32")
}

func (v int32Value) Uint8() uint8 {
	panic("cannot get uint8 out of int32")
}

func (v int32Value) Uint16() uint16 {
	panic("cannot get uint16 out of int32")
}

func (v int32Value) Uint32() uint32 {
	panic("cannot get uint32 out of int32")
}

func (v int32Value) Uint64() uint64 {
	panic("cannot get uint64 out of int32")
}

func (v int32Value) Bool() bool {
	panic("cannot get bool out of int32")
}

func (v int32Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type int64Value struct {
	v int64
}

func (v int64Value) Type() Type {
	return Int64
}

func (v int64Value) Get() interface{} {
	return v.v
}

func (v int64Value) IsNull() bool {
	return false
}

func (v int64Value) Int() int {
	panic("cannot get int out of int64")
}

func (v int64Value) Int8() int8 {
	panic("cannot get int8 out of int64")
}

func (v int64Value) Int16() int16 {
	panic("cannot get int16 out of int64")
}

func (v int64Value) Int32() int32 {
	panic("cannot get int32 out of int64")
}

func (v int64Value) Int64() int64 {
	return v.v
}

func (v int64Value) Uint() uint {
	panic("cannot get uint out of int64")
}

func (v int64Value) Uint8() uint8 {
	panic("cannot get uint8 out of int64")
}

func (v int64Value) Uint16() uint16 {
	panic("cannot get uint16 out of int64")
}

func (v int64Value) Uint32() uint32 {
	panic("cannot get uint32 out of int64")
}

func (v int64Value) Uint64() uint64 {
	panic("cannot get uint64 out of int64")
}

func (v int64Value) Bool() bool {
	panic("cannot get bool out of int64")
}

func (v int64Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type uintValue struct {
	v uint
}

func (v uintValue) Type() Type {
	return Uint
}

func (v uintValue) Get() interface{} {
	return v.v
}

func (v uintValue) IsNull() bool {
	return false
}

func (v uintValue) Int() int {
	panic("cannot get int out of uint")
}

func (v uintValue) Int8() int8 {
	panic("cannot get int8 out of uint")
}

func (v uintValue) Int16() int16 {
	panic("cannot get int16 out of uint")
}

func (v uintValue) Int32() int32 {
	panic("cannot get int32 out of uint")
}

func (v uintValue) Int64() int64 {
	panic("cannot get int64 out of uint")
}

func (v uintValue) Uint() uint {
	return v.v
}

func (v uintValue) Uint8() uint8 {
	panic("cannot get uint8 out of uint")
}

func (v uintValue) Uint16() uint16 {
	panic("cannot get uint16 out of uint")
}

func (v uintValue) Uint32() uint32 {
	panic("cannot get uint32 out of uint")
}

func (v uintValue) Uint64() uint64 {
	panic("cannot get uint64 out of uint")
}

func (v uintValue) Bool() bool {
	panic("cannot get bool out of uint")
}

func (v uintValue) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type uint8Value struct {
	v uint8
}

func (v uint8Value) Type() Type {
	return Uint8
}

func (v uint8Value) Get() interface{} {
	return v.v
}

func (v uint8Value) IsNull() bool {
	return false
}

func (v uint8Value) Int() int {
	panic("cannot get int out of uint8")
}

func (v uint8Value) Int8() int8 {
	panic("cannot get int8 out of uint8")
}

func (v uint8Value) Int16() int16 {
	panic("cannot get int16 out of uint8")
}

func (v uint8Value) Int32() int32 {
	panic("cannot get int32 out of uint8")
}

func (v uint8Value) Int64() int64 {
	panic("cannot get int64 out of uint8")
}

func (v uint8Value) Uint() uint {
	panic("cannot get uint out of uint8")
}

func (v uint8Value) Uint8() uint8 {
	return v.v
}

func (v uint8Value) Uint16() uint16 {
	panic("cannot get uint16 out of uint8")
}

func (v uint8Value) Uint32() uint32 {
	panic("cannot get uint32 out of uint8")
}

func (v uint8Value) Uint64() uint64 {
	panic("cannot get uint64 out of uint8")
}

func (v uint8Value) Bool() bool {
	panic("cannot get bool out of uint8")
}

func (v uint8Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type uint16Value struct {
	v uint16
}

func (v uint16Value) Type() Type {
	return Uint16
}

func (v uint16Value) Get() interface{} {
	return v.v
}

func (v uint16Value) IsNull() bool {
	return false
}

func (v uint16Value) Int() int {
	panic("cannot get int out of uint16")
}

func (v uint16Value) Int8() int8 {
	panic("cannot get int8 out of uint16")
}

func (v uint16Value) Int16() int16 {
	panic("cannot get int16 out of uint16")
}

func (v uint16Value) Int32() int32 {
	panic("cannot get int32 out of uint16")
}

func (v uint16Value) Int64() int64 {
	panic("cannot get int64 out of uint16")
}

func (v uint16Value) Uint() uint {
	panic("cannot get uint out of uint16")
}

func (v uint16Value) Uint8() uint8 {
	panic("cannot get uint8 out of uint16")
}

func (v uint16Value) Uint16() uint16 {
	return v.v
}

func (v uint16Value) Uint32() uint32 {
	panic("cannot get uint32 out of uint16")
}

func (v uint16Value) Uint64() uint64 {
	panic("cannot get uint64 out of uint16")
}

func (v uint16Value) Bool() bool {
	panic("cannot get bool out of uint16")
}

func (v uint16Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type uint32Value struct {
	v uint32
}

func (v uint32Value) Type() Type {
	return Uint32
}

func (v uint32Value) Get() interface{} {
	return v.v
}

func (v uint32Value) IsNull() bool {
	return false
}

func (v uint32Value) Int() int {
	panic("cannot get int out of uint32")
}

func (v uint32Value) Int8() int8 {
	panic("cannot get int8 out of uint32")
}

func (v uint32Value) Int16() int16 {
	panic("cannot get int16 out of uint32")
}

func (v uint32Value) Int32() int32 {
	panic("cannot get int32 out of uint32")
}

func (v uint32Value) Int64() int64 {
	panic("cannot get int64 out of uint32")
}

func (v uint32Value) Uint() uint {
	panic("cannot get uint out of uint32")
}

func (v uint32Value) Uint8() uint8 {
	panic("cannot get uint8 out of uint32")
}

func (v uint32Value) Uint16() uint16 {
	panic("cannot get uint16 out of uint32")
}

func (v uint32Value) Uint32() uint32 {
	return v.v
}

func (v uint32Value) Uint64() uint64 {
	panic("cannot get uint64 out of uint32")
}

func (v uint32Value) Bool() bool {
	panic("cannot get bool out of uint32")
}

func (v uint32Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type uint64Value struct {
	v uint64
}

func (v uint64Value) Type() Type {
	return Uint64
}

func (v uint64Value) Get() interface{} {
	return v.v
}

func (v uint64Value) IsNull() bool {
	return false
}

func (v uint64Value) Int() int {
	panic("cannot get int out of uint64")
}

func (v uint64Value) Int8() int8 {
	panic("cannot get int8 out of uint64")
}

func (v uint64Value) Int16() int16 {
	panic("cannot get int16 out of uint64")
}

func (v uint64Value) Int32() int32 {
	panic("cannot get int32 out of uint64")
}

func (v uint64Value) Int64() int64 {
	panic("cannot get int64 out of uint64")
}

func (v uint64Value) Uint() uint {
	panic("cannot get uint out of uint64")
}

func (v uint64Value) Uint8() uint8 {
	panic("cannot get uint8 out of uint64")
}

func (v uint64Value) Uint16() uint16 {
	panic("cannot get uint16 out of uint64")
}

func (v uint64Value) Uint32() uint32 {
	panic("cannot get uint32 out of uint64")
}

func (v uint64Value) Uint64() uint64 {
	return v.v
}

func (v uint64Value) Bool() bool {
	panic("cannot get bool out of uint64")
}

func (v uint64Value) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type stringValue struct {
	v string
}

func (v stringValue) Type() Type {
	return String
}

func (v stringValue) Get() interface{} {
	return v.v
}

func (v stringValue) IsNull() bool {
	return false
}

func (v stringValue) Int() int {
	panic("cannot get int out of string")
}

func (v stringValue) Int8() int8 {
	panic("cannot get int8 out of string")
}

func (v stringValue) Int16() int16 {
	panic("cannot get int16 out of string")
}

func (v stringValue) Int32() int32 {
	panic("cannot get int32 out of string")
}

func (v stringValue) Int64() int64 {
	panic("cannot get int64 out of string")
}

func (v stringValue) Uint() uint {
	panic("cannot get uint out of string")
}

func (v stringValue) Uint8() uint8 {
	panic("cannot get uint8 out of string")
}

func (v stringValue) Uint16() uint16 {
	panic("cannot get uint16 out of string")
}

func (v stringValue) Uint32() uint32 {
	panic("cannot get uint32 out of string")
}

func (v stringValue) Uint64() uint64 {
	panic("cannot get uint64 out of string")
}

func (v stringValue) Bool() bool {
	panic("cannot get bool out of string")
}

func (v stringValue) String() string {
	return fmt.Sprintf("%v", v.Get())
}

type boolValue struct {
	v bool
}

func (v boolValue) Type() Type {
	return Bool
}

func (v boolValue) Get() interface{} {
	return v.v
}

func (v boolValue) IsNull() bool {
	return false
}

func (v boolValue) Int() int {
	panic("cannot get int out of bool")
}

func (v boolValue) Int8() int8 {
	panic("cannot get int8 out of bool")
}

func (v boolValue) Int16() int16 {
	panic("cannot get int16 out of bool")
}

func (v boolValue) Int32() int32 {
	panic("cannot get int32 out of bool")
}

func (v boolValue) Int64() int64 {
	panic("cannot get int64 out of bool")
}

func (v boolValue) Uint() uint {
	panic("cannot get uint out of bool")
}

func (v boolValue) Uint8() uint8 {
	panic("cannot get uint8 out of bool")
}

func (v boolValue) Uint16() uint16 {
	panic("cannot get uint16 out of bool")
}

func (v boolValue) Uint32() uint32 {
	panic("cannot get uint32 out of bool")
}

func (v boolValue) Uint64() uint64 {
	panic("cannot get uint64 out of bool")
}

func (v boolValue) Bool() bool {
	return v.v
}

func (v boolValue) String() string {
	return fmt.Sprintf("%v", v.Get())
}

func NewValue(v interface{}) Value {
	if v == nil {
		panic("cannot create value from nil")
	}
	switch v := v.(type) {
	case int:
		return intValue{v: v}
	case int8:
		return int8Value{v: v}
	case int16:
		return int16Value{v: v}
	case int32:
		return int32Value{v: v}
	case int64:
		return int64Value{v: v}
	case uint:
		return uintValue{v: v}
	case uint8:
		return uint8Value{v: v}
	case uint16:
		return uint16Value{v: v}
	case uint32:
		return uint32Value{v: v}
	case uint64:
		return uint64Value{v: v}
	case string:
		return stringValue{v: v}
	case bool:
		return boolValue{v: v}
	default:
		panic(fmt.Errorf("cannot create value from type %T", v))
	}
}

type nullValue struct {
	t Type
}

func NewNull(t Type) Value {
	return nullValue{t: t}
}

func (v nullValue) Type() Type {
	return v.t
}

func (v nullValue) Get() interface{} {
	return nil
}

func (v nullValue) IsNull() bool {
	return true
}

func (v nullValue) Int() int {
	panic("cannot get int out of null value")
}

func (v nullValue) Int8() int8 {
	panic("cannot get int8 out of null value")
}

func (v nullValue) Int16() int16 {
	panic("cannot get int16 out of null value")
}

func (v nullValue) Int32() int32 {
	panic("cannot get int32 out of null value")
}

func (v nullValue) Int64() int64 {
	panic("cannot get int64 out of null value")
}

func (v nullValue) Uint() uint {
	panic("cannot get uint out of null value")
}

func (v nullValue) Uint8() uint8 {
	panic("cannot get uint8 out of null value")
}

func (v nullValue) Uint16() uint16 {
	panic("cannot get uint16 out of null value")
}

func (v nullValue) Uint32() uint32 {
	panic("cannot get uint32 out of null value")
}

func (v nullValue) Uint64() uint64 {
	panic("cannot get uint64 out of null value")
}

func (v nullValue) Bool() bool {
	panic("cannot get bool out of null value")
}

func (v nullValue) String() string {
	return "nil"
}
