on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x] # , 1.14.x]
        # cannot run on MacOS:
        #  Run actions-contrib/golangci-lint@v1
        #  [error]Container action is only supported on Linux
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: actions-contrib/golangci-lint@v1
    - name: Test
      run: go test ./...
